### ISSUE TITLE
Dominoes - nice simulator, but...

### ISSUE THREAD

**Issue by ghost** [swilly22/dominos#1]
Unfortunately, the Gallery and Share options do not appear to be working at present.

=====
I would like to use the Dominoes simulator so I can model and set puzzles in BINARY logic for students.

Would it be possible to create a self-referencing URL with the model 64-encoded as part of the URL, so there is no central server requirement. (Sorry I would try to code this myself, but am having to write 3 schemes of work for Computer Science at present).

**Comment by swilly22** [comment]
Hi @pelboothroyd,
It's been quite some time since I've touched this project, so I'll have to refresh my memory, unfortunately, currently I don't have the capacity to do that.
